FROM debian:latest as parinfer

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
            curl \
            gnupg \
            gpm \
            clang \
            cargo 

RUN apt-get install -y git 
RUN cd tmp/ && git clone https://github.com/eraserhd/parinfer-rust.git 
RUN cd /tmp/parinfer-rust && cargo build --release

